### ISSUE TITLE
Pop gesture not working when there is horizontal scrolling view.

### ISSUE THREAD

**Issue by curno** [fastred/AHKNavigationController#3]
When there is a horizontal scroll view attached to the left edge, the pop gesture will not work because the events are handled by the scroll view's scrolling gesture. Maybe u want to add the following code: 

  - (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldBeRequiredToFailByGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
    return YES;
  }

Also, an option to turn this feature on/off will be nice! :)

**Comment by fastred** [comment]
Good idea! Could you create a pull request with implementation?

**Comment by curno** [comment]
I create a pull request to fix this issue. Please check it when you have time.

**Comment by minchaej** [comment]
Wow awesome!!! Is this fixed?? How can I do it on AHKNavigationController?

**Comment by cprovatas** [comment]
@minchaej The PR was never reviewed and was closed.
https://github.com/fastred/AHKNavigationController/pull/4
